apiVersion: v1
kind: Service
metadata:
  name: kubewatch-intermediary-service
  namespace: kubewatch
spec:
  selector:
    app: kubewatch-intermediary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP